server:
  host: "0.0.0.0"
  port: 8080

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "pip64"
  password: "1234"
  dbname: "bloom"

jwt:
  secret: "coolsecret"
  expire_hours: 8760

argon2:
  time: 1
  memory: 16384
  threads: 4
  key_len: 32

rate_limit:
  enabled: true
  auth_requests_per_minute: 5
  general_requests_per_minute: 60
  window_minutes: 1
